# Generated by Django 5.1.7 on 2025-03-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Szolgaltatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=126)),
                ('ar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leiras', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idopont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('ido', models.TimeField()),
                ('foglalt', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('szolgaltatas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.szolgaltatas')),
            ],
            options={
                'unique_together': {('datum', 'ido')},
            },
        ),
    ]
