# Generated by Django 5.1.7 on 2025-03-27 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idopont',
            name='foglalt',
        ),
        migrations.RemoveField(
            model_name='idopont',
            name='szolgaltatas',
        ),
        migrations.RemoveField(
            model_name='idopont',
            name='user',
        ),
        migrations.CreateModel(
            name='Foglalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idopont', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.idopont')),
                ('szolgaltatas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.szolgaltatas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
