# Generated by Django 5.1.7 on 2025-03-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_idopont_foglalt_remove_idopont_szolgaltatas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idopont',
            name='foglalt',
            field=models.BooleanField(default=False),
        ),
    ]
