# Generated by Django 5.1.7 on 2025-12-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_idopont_foglalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='foglalas',
            name='tapasztalat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
